name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backends:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['order-service', 'bff', 'category-service', 'product-service', 'auth']
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          ./mvnw test
      - name: Build and Test ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          ./mvnw package

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Frontend
        run: |
          cd front
          npm install
          npm run build

  docker-push:
    needs: [build-backends, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Images
        run: |
          export TAG=ghcr.io/${{ github.repository_owner }}/order-service:latest
          docker build -t $TAG ./order-service
          docker push $TAG
          # Repita para outros serviços e frontend